### ISSUE TITLE
Modernize examples

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/minpack#32]
The current tests are not actually testing anything other than running the examples. They provide no way to check the results other than by manual inspection, which makes them not reliable as regression tests.

Required steps:

- split the objective functions in separate callbacks rather than one big select case via a common block variable
- have a resource module to hold the objective functions and initializers to avoid code duplication
- actually test the outcome of the examples is correct up to a given tolerance

**Comment by cbouilla** [comment]
Dear all, I have been hit by the same issue. I have solved it as follows (https://github.com/cbouilla/minpack-1.1). Update the test programs to compare the output with the values given in the "Algorithm 566, ACM TOMS" paper, up to a fixed tolerance. I originally 1e-6, but it turns out that apparently mundane changes (BLAS `dnrm2` instead or `enorm`) alter the result too much, so I had to use 1e-5. Having tests that pass/fail is invaluable.

Feel free to steal my code.
